// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoLIstAPi.DbContext;

#nullable disable

namespace ToDoLIstAPi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120150558_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Write the project documentation for the new API.",
                            DueDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Complete Documentation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Develop the user authentication feature for the app.",
                            DueDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Implement New Feature",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Resolve the issue with the login API endpoint.",
                            DueDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Fix Bug in API",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Modify the database schema for the new feature.",
                            DueDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Update Database Schema",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Refactor the codebase to improve performance and readability.",
                            DueDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Refactor Code",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Review the code submitted by the team for the latest feature.",
                            DueDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Conduct Code Review",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Write unit tests for the new user profile feature.",
                            DueDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Write Unit Tests",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Deploy the application to the staging environment.",
                            DueDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Deploy Application",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Backup all the relevant databases before the deployment.",
                            DueDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Create Database Backups",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Organize and plan the tasks for the upcoming sprint.",
                            DueDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Plan Sprint",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yassine",
                            position = "Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fatima",
                            position = "Project Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ahmed",
                            position = "Data Scientist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sara",
                            position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ali",
                            position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Noor",
                            position = "QA Engineer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hassan",
                            position = "Mobile Developer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mounia",
                            position = "Business Analyst"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ibrahim",
                            position = "Backend Developer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Amina",
                            position = "Frontend Developer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Khalid",
                            position = "Database Administrator"
                        });
                });

            modelBuilder.Entity("Models.Entities.Tasks", b =>
                {
                    b.HasOne("Models.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
