@ToDoLIstAPi_HostAddress = http://localhost:5089

GET {{ToDoLIstAPi_HostAddress}}/weatherforecast/
Accept: application/json

###
###&
POST {{ToDoLIstAPi_HostAddress}}/api/user
Content-Type: application/json
#Basic dGVzdDoxMjM=
{
    "Name" : "testpost" , 
    "position" : "leader" , 
    "Username" :"test" , 
    "Password" :"123" , 
    "Role" : "sidek", 
    "Tasks" : []
}

#med:med Basic bWVkOm1lZA==

